### ISSUE TITLE
Unable to scroll/pan until there's at least one tag

### ISSUE THREAD

**Issue by EthanMarsh** [neurala/Grounder#23]
Quote from customer: "I can’t seem to be able to scroll (a.k.a pan) through an image until I’ve tagged something in it. I can create a tag, delete it and be able to scroll just fine, so it’s likely some sort of initialization issue."

**Comment by NevesLucas** [comment]
can't replicate on my version, perhaps its already fixed for next release, will check again once packaged

**Comment by NevesLucas** [comment]
bug identified: user must click on image to make it the active workspace and bind hotkeys
